# Generated by Django 3.2.12 on 2022-05-01 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.CharField(blank=True, max_length=1000)),
                ('myKey', models.TextField(null=True)),
                ('myList', models.TextField(null=True)),
            ],
        ),
    ]
